# Lab 8 - Iterative Methods for Linear Systems
## April 10 - April 12, 2023
## Student 1 Name: $\underline{KANISHK \ DAD\hspace{3in}}$ Student 1 ID No. $\underline{202103005\hspace{1.5in}}$
## Student 2 Name: $\underline{ADITYA \ \ TANNA\hspace{3in}}$ Student 2 ID No. $\underline{202103023\hspace{1.5in}}$
## Student 3 Name: $\underline{VRAJ THAKKAR\hspace{3in}}$ Student 3 ID No. $\underline{202103052\hspace{1.5in}}$
## Date of Submission: $\underline{12/04/23}$
***

In [144]:
# import useful libraries
import numpy as np
import matplotlib.pyplot as plt
import math
epsilon  = .00000000000000000001

In [153]:
# A = [[144,12,2],
#      [8,64,1],
#      [5,1,2]]
# Y = [[280.2],
#      [177.2],
#      [106.8]]


A = [[12, 5, 2, 4],[3, 10, 4, 2],[3, 4, 10, 2],[1, 2, 3, 7]]
Y = [[3],
     [5],
     [4],
     [1]]
    

x_for_list = np.linalg.solve(A,Y)
print(x_for_list)

[[ 0.07119741]
 [ 0.4012945 ]
 [ 0.23462783]
 [-0.08252427]]


### Q.1 Write a function `myfwdsubstituion` that takes in an lower triangular matrix  $L \in \mathbb{R}^{n \times n}$, a vector $b \in \mathbb{R}^{n \times 1}$ and returns the solution $x$ of $Lx = b$ obtained by forward substitution.

In [154]:
def myfwdsubstitution(P,b):
    n = len(P)
    x = np.zeros((n, 1))
    sum_L = 0 
    for i in range(n):
        sum_L = 0
        for j in range(i):
            sum_L = sum_L + P[i][j]*x[j]
        x[i] = (b[i]-sum_L)/P[i][i]
    return x

***
### Q.2 Write a function `myGS` that solves a linear system of equations iteratively using the Gauss-Seidel method using the function `myfwsubstitution` written above. The function accepts the matrix $A \in \mathbb{R}^{n \times n}$, the vector $b \in \mathbb{R}^n$, and returns the solution to $Ax=b$. The stopping criteria could be to check $\frac{||x_{k+1}-x_k||}{||x_k||+\epsilon}$, where $\epsilon$ is a small number that ensures that the denominator does not go to zero.

In [155]:
def myGS(A,Y):
    n = len(A)
    ddm  = np.zeros((n,1))
    for i in range(n):
        for j in range(n):
            ddm[i]= ddm[i] + abs(A[i][j])
        ddm[i]= ddm[i] - 2*abs(A[i][i])
    print('criteria to check diagonally dominant matrix = ',ddm)

    U = np.zeros((n, n))
    L = np.zeros((n, n))
    D = np.zeros((n, n))
#function to calculate lower triangular matrix
    def L_of_A(A):
        for i in range(n):
            for j in range(i):
                L[i][j]= A[i][j]
        return L

#function to calculate lower triangular matrix
    def D_of_A(A):
        for i in range(n):
                D[i][i]= A[i][i]
        return D
    
#function to calculate upper triangular matrix
    def U_of_A(A):
        for i in range(n):
            for j in range(i+1,n):
                U[i][j]= -A[i][j]
        return U
#calculating P and Q
    P = L_of_A(A) + D_of_A(A)
    Q = U_of_A(A)

    # P*X = Q*Xo +b        "gauss seidel formula"
    Xn = np.zeros((n, 1))
    error = Xo = np.ones((n,1))
    Iteration = 0
    condition = True
    while (condition):
        b= Q @ Xo+ Y
# Using the function myfwsubstitution(A,b)
        Xn = myfwdsubstitution(P,b)
        # print(Xo)
        # print(Xn)
        # print(error)

# stopping criteria
        error = Xn - Xo
        ddm  = np.zeros((n,1))
        for i in range(n):
            ddm[i]= ddm[i] + abs(error[i])
        for i in range(n):
            if ((max(ddm)/(max(Xo)+epsilon)) < epsilon):
                condition = False
# another stopping criteria

        # error = Xn - Xo
        # e =[1,1,1,1]
        # for i in range(n):
        #     e[i] = Xn[i] - Xo[i]
        #     if (abs(e[i]) < epsilon):
        #         condition = False

        Xo = Xn
        Iteration += 1
    print(Xn,Iteration)
    return Xn,Iteration

In [156]:
Xn,Iteration = myGS(A,Y)
# print("solution matrix", Xn)
# print("No. of Iteration required = ",Iteration)

criteria to check diagonally dominant matrix =  [[-1.]
 [-1.]
 [-1.]
 [-1.]]
[[ 0.07119741]
 [ 0.4012945 ]
 [ 0.23462783]
 [-0.08252427]] 30


***
### Q.3 Write a function `myJacobi` that solves a linear system of equations iteratively using the Jacobi method. The function accepts the matrix $A \in \mathbb{R}^{n \times n}$, the vector $b \in \mathbb{R}^n$, and returns the solution to $Ax=b$. The stopping criteria could be to check $\frac{||x_{k+1}-x_k||}{||x_k||+\epsilon}$, where $\epsilon$ is a small number that ensures that the denominator does not go to zero.

In [161]:

# A = np.array([[144,12,2],[8,64,1],[5,1,2]])
# Y = np.array([[280.2],[177.2],[106.8]])

A = np.array([[12, 5, 2, 4],[3, 10, 4, 2],[3, 4, 10, 2],[1, 2, 3, 7]])
Y = np.array([[3],[5],[4],[1]])


x = np.linalg.solve(A,Y)
print(x)

[[ 0.07119741]
 [ 0.4012945 ]
 [ 0.23462783]
 [-0.08252427]]


In [162]:

def myJacobi(A, b):
    epsilon=1e-10
    max_iterations=1000
    n = A.shape[0]
    x = np.zeros(n)
    x_next = np.zeros(n)
    for i in range(max_iterations):
        for j in range(n):
            s = 0
            for k in range(n):
                if k != j:
                    s += A[j, k] * x[k]
            x_next[j] = (b[j] - s) / A[j, j]
        if np.linalg.norm(x_next - x) / (np.linalg.norm(x) + epsilon) < epsilon:
            break
        
        x = x_next.copy()
    return x,i

In [163]:
Xn1, Iteration1 = myJacobi(A,Y)
print(Xn1,Iteration1)

[ 0.07119741  0.4012945   0.23462783 -0.08252427] 211


***
### Q.4 Construct a few matrices that are diagonally dominant, for eg: $A = \left[\begin{array}{ccccc}
5 & -1 & 0 & \ldots & -1 \\
-1 & 5 & -1 & \ldots & 0 \\
\vdots & \vdots & \vdots & \ldots & \vdots \\
0 & 0 & 0 & \ldots & 5
\end{array}\right]$ and vectors $b$, and solve the sytem $Ax=b$ using `myGS`,`myJacobi`, and `np.linalg.solve`. Compare the solutions, iterations and the time taken to solve the system. Also note the error in the solution, assuming that the `numpy.linalg.solve` produces the true solution

In [164]:

### Construct examples of A,b and solve using the three methods mentioned above. 
### Compare the solutions obtained.

error_in_GS = Xn - x_for_list
no_of_iteration_in_GS = Iteration 
print('max_error_in_GS =',max(abs(error_in_GS)))
print('Iteration_in_GS=',Iteration,'\n')

# error_in_Jacobi = Xn1 - x
# print(error_in_Jacobi)
no_of_iteration_in_Jacobi = Iteration1
print(Xn1[2])
print(x[2])
# k=max(abs(error_in_Jacobi))
# print('error_in_Jacobi =',k)
print('Iteration_in_Jacobi=',Iteration1)

max_error_in_GS = [5.55111512e-17]
Iteration_in_GS= 30 

0.23462783172684923
[0.23462783]
Iteration_in_Jacobi= 211
